shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - rollup@2.80.0
  - semver@6.3.1
  - chokidar@4.0.3

packages: []
catalogs:
  build:
    '@nuxt/devtools': ^3.1.1
    '@nuxt/eslint': ^1.14.0
    '@nuxt/kit': ^4.3.1
    '@nuxtjs/color-mode': ^4.0.0
    '@pinia/nuxt': ^0.11.3
    '@unocss/eslint-config': ^66.6.0
    '@unocss/nuxt': ^66.6.0
    '@vite-pwa/nuxt': ^1.1.1
    '@vueuse/nuxt': ^14.2.0
    nuxt: ^4.3.1
    unocss: ^66.6.0
    unplugin: ^3.0.0
    vite: ^7.3.1
  dev:
    '@antfu/eslint-config': ^7.3.0
    '@types/node': ^25.2.2
    eslint: ^9.39.2
    eslint-plugin-format: ^1.4.0
    typescript: ^5.9.3
    vue-tsc: ^3.2.4
  frontend:
    '@vueuse/core': ^14.2.0
    pinia: ^3.0.4
    vue: ^3.5.27
  icons:
    '@iconify-json/carbon': ^1.2.18
    '@iconify-json/twemoji': ^1.2.5
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver
