/**
 * ---------------------
 * 🚗🚦 Generated by nuxt-typed-router. Do not modify !
 * ---------------------
 * */

import { defineNuxtPlugin } from '#app'

export default defineNuxtPlugin((nuxtApp) => {
  const routesList = {
    '404': '404',
    hiId: 'hi-id',
    index: 'index',
    restfulPageView: 'restful-page-view',
  }

  return {
    provide: {
      typedRouter: nuxtApp.$router,
      routesList,
    },
  }
})
