<script setup lang="ts">
import { useCountryQuery, usePersonQuery } from '~/generated/graphql/operations' // generated by @nuxt3/graphql-codegen-module

const { result: client, loading: queryLoading } = useCountryQuery({
  clientId: 'trevorblades',
  prefetch: false, // clientMode, need validate result in template
})

const {
  result: server,
  loading: jumpLoading,
  error,
} = usePersonQuery(
  {
    personInput: {
      name: 'Phil Xu',
    },
  },
  {
    prefetch: true, // ssrMode, default: true
  },
)

// use clients directly $apollo.default  $apollo.trevorblades
// const { $apollo } = useNuxtApp()
</script>

<template>
  <div>
    <div>
      <h3 text-2xl font-500>Graphql Api</h3>
      <div v-show="queryLoading">
        {{ $t('clientLoading') }}
      </div>
      <div v-if="client && client.country">
        {{ $t('clientMode') }}: {{ $t(client.country.name) }}
      </div>

      <div v-show="jumpLoading">
        {{ $t('ssrLoading') }}
      </div>
      <div v-if="server && server.person">
        {{ $t('ssrMode') }}: {{ $t(server.person.name) }}
      </div>
      <div v-else-if="error">
        {{ error }}
      </div>

      <div>
        <NuxtLink class="btn m-3 text-sm" to="/restful/page-view">
          RESTful Api
        </NuxtLink>
      </div>
    </div>
  </div>
</template>
